# Run me in development!
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.local
      target: php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports: [ "8000:8000" ]
