# Run me in production!
services:
   # Database Server
    database:
        container_name: mysql
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=default
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes: [ db-data:/var/lib/mysql ]
    # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
        working_dir: /var/www
        ports: [ "80:80" ]
        depends_on: [ database ]
volumes:
    db-data: ~
