services:
   # Database Server
    database:
        container_name: mysql
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
    # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
        working_dir: /var/www
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - database
volumes:
    db-data: ~
